[2025-04-01T19:29:37.715+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-01T19:24:32.076029+00:00 [queued]>
[2025-04-01T19:29:37.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-01T19:24:32.076029+00:00 [queued]>
[2025-04-01T19:29:37.719+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-01T19:29:37.724+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-01 19:24:32.076029+00:00
[2025-04-01T19:29:37.732+0000] {standard_task_runner.py:60} INFO - Started process 527 to run task
[2025-04-01T19:29:37.736+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_a', 'load_data', 'manual__2025-04-01T19:24:32.076029+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmpl73iyl4p']
[2025-04-01T19:29:37.737+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask load_data
[2025-04-01T19:29:37.773+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_a.load_data manual__2025-04-01T19:24:32.076029+00:00 [running]> on host b0ef469a0134
[2025-04-01T19:29:37.830+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_a' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T19:24:32.076029+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T19:24:32.076029+00:00'
[2025-04-01T19:29:37.835+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-01T19:29:37.930+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-01T19:29:37.935+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_a, task_id=load_data, execution_date=20250401T192432, start_date=20250401T192937, end_date=20250401T192937
[2025-04-01T19:29:37.954+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T19:29:37.963+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
