[2025-04-02T10:05:32.189+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-02T08:02:43.077536+00:00 [queued]>
[2025-04-02T10:05:32.193+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-02T08:02:43.077536+00:00 [queued]>
[2025-04-02T10:05:32.193+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-02T10:05:32.198+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-02 08:02:43.077536+00:00
[2025-04-02T10:05:32.203+0000] {standard_task_runner.py:60} INFO - Started process 2673 to run task
[2025-04-02T10:05:32.205+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_a', 'load_data', 'manual__2025-04-02T08:02:43.077536+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmpp4dl8luf']
[2025-04-02T10:05:32.206+0000] {standard_task_runner.py:88} INFO - Job 58: Subtask load_data
[2025-04-02T10:05:32.228+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_a.load_data manual__2025-04-02T08:02:43.077536+00:00 [running]> on host f4b0101fc635
[2025-04-02T10:05:32.269+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_a' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T08:02:43.077536+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T08:02:43.077536+00:00'
[2025-04-02T10:05:32.274+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-02T10:05:32.390+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-02T10:05:32.394+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_a, task_id=load_data, execution_date=20250402T080243, start_date=20250402T100532, end_date=20250402T100532
[2025-04-02T10:05:32.422+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-02T10:05:32.434+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
