[2025-04-01T18:37:59.045+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-01T18:37:56.209073+00:00 [queued]>
[2025-04-01T18:37:59.049+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-01T18:37:56.209073+00:00 [queued]>
[2025-04-01T18:37:59.050+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-01T18:37:59.057+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-01 18:37:56.209073+00:00
[2025-04-01T18:37:59.065+0000] {standard_task_runner.py:60} INFO - Started process 695 to run task
[2025-04-01T18:37:59.068+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_a', 'load_data', 'manual__2025-04-01T18:37:56.209073+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmpqkaje20r']
[2025-04-01T18:37:59.069+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask load_data
[2025-04-01T18:37:59.093+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_a.load_data manual__2025-04-01T18:37:56.209073+00:00 [running]> on host d03c7c3d6af6
[2025-04-01T18:37:59.123+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_a' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T18:37:56.209073+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T18:37:56.209073+00:00'
[2025-04-01T18:37:59.128+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-01T18:37:59.236+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-01T18:37:59.241+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_a, task_id=load_data, execution_date=20250401T183756, start_date=20250401T183759, end_date=20250401T183759
[2025-04-01T18:37:59.281+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T18:37:59.293+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
